spring:
  application:
    name: springcloud-service-provider
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    #GMT%2B8代表： 东八区
    username: spring_cloud
    password: spring_cloud
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    database: 1
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
server:
  port: 8085
#eureka的配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
mybatis:
  mapperLocations: classpath:mapperconfig/*.xml
  typeAliasesPackage: com.springcloud.mapper
#日志输出mybatis里面的sql
logging:
  level:
    com.hrq.springcloud.mapper: debug